import React, { useState } from 'react';
import { Target, AlertTriangle, Lightbulb, Globe2, Wallet, CheckCircle, TrendingUp, X, Check, FileText, Download, Loader2, Sparkles } from 'lucide-react';
import { GlassCard } from '@/components/ui/GlassCard';
import { SafeCountUp as CountUp } from '@/components/ui/SafeCountUp';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { motion, AnimatePresence } from 'framer-motion';
import { toast } from 'react-hot-toast';

const financialData = [
  { month: 'Jan', revenue: 4000, target: 3800 },
  { month: 'Feb', revenue: 4500, target: 4000 },
  { month: 'Mar', revenue: 5200, target: 4500 },
  { month: 'Apr', revenue: 4800, target: 4800 },
  { month: 'May', revenue: 6100, target: 5200 },
  { month: 'Jun', revenue: 6800, target: 5800 },
];

const INITIAL_DECISIONS = [
  {
    id: 'dec-1',
    title: 'M&A Opportunity: TechNova',
    desc: 'Strategic acquisition alignment score: 88%. Board requires CEO approval to proceed to term sheet.',
    fullDetail: 'Acquisition of TechNova (SaaS CRM platform) for $4.2M. Projected integration timeframe: 90 days. Estimated ARR addition: $1.2M. Key risks: Platform migration timeline and team transition overlap.',
    alignmentScore: '88%'
  },
  {
    id: 'dec-2',
    title: 'Approve Q4 Marketing Budget',
    desc: 'CMO requesting 15% increase for APAC expansion.',
    fullDetail: 'Request for additional $180,000 for localizing ad spend in Japan and Singapore. AI analysis shows localized APAC campaigns return 4.2x ROI vs 2.1x in domestic markets.',
    alignmentScore: '92%'
  },
  {
    id: 'dec-3',
    title: 'Vendor Contract Renewal',
    desc: 'Cloud provider contract up for renewal. Options: 1-yr vs 3-yr commitment.',
    fullDetail: '3-year commitment saves $45,000/yr but offers less flexibility. AI recommends 1-year contract due to migration targets to serverless next year.',
    alignmentScore: '74%'
  },
  {
    id: 'dec-4',
    title: 'Office Space Consolidation',
    desc: 'Consolidate Austin satellite office into HQ to reduce footprint by 20%.',
    fullDetail: 'Saves $12,000/month in lease costs. 85% of Austin employees prefer remote/hybrid. Low impact on productivity predicted.',
    alignmentScore: '85%'
  }
];

function BoardReportModal({ onClose }) {
  const [downloading, setDownloading] = useState(false);

  const handleDownload = () => {
    setDownloading(true);
    setTimeout(() => {
      setDownloading(false);
      toast.success('Executive Board Report PDF downloaded! 📄');
    }, 1500);
  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm"
      onClick={onClose}
    >
      <motion.div
        initial={{ scale: 0.92, y: 20, opacity: 0 }}
        animate={{ scale: 1, y: 0, opacity: 1 }}
        exit={{ scale: 0.92, y: 20, opacity: 0 }}
        transition={{ type: 'spring', stiffness: 300, damping: 28 }}
        className="w-full max-w-2xl bg-[#0B1120] border border-white/10 rounded-3xl shadow-[0_30px_80px_rgba(0,0,0,0.8)] overflow-hidden"
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div className="px-6 py-5 border-b border-white/5 flex items-center justify-between bg-gradient-to-r from-[#EC4899]/10 to-[#5B5FFF]/10">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-gradient-to-tr from-[#EC4899] to-[#5B5FFF] flex items-center justify-center shadow-[0_0_15px_rgba(236,72,153,0.4)]">
              <FileText size={18} className="text-white" />
            </div>
            <div>
              <h2 className="text-base font-bold text-white font-display">Executive Board Report</h2>
              <p className="text-xs text-[#94A3B8]">Generated by AI Copilot for Board review</p>
            </div>
          </div>
          <button onClick={onClose} className="functional-btn p-2 rounded-xl text-[#94A3B8] hover:text-white hover:bg-white/10 transition-colors">
            <X size={18} />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 space-y-5 max-h-[60vh] overflow-y-auto custom-scrollbar">
          <div className="p-4 rounded-2xl bg-white/5 border border-white/5 space-y-3">
            <h3 className="text-sm font-bold text-[#EC4899] uppercase tracking-wider flex items-center gap-1.5">
              <Sparkles size={14} /> Executive Summary
            </h3>
            <p className="text-sm text-white/90 leading-relaxed">
              Business Brain is performing exceptionally well in Q3. Revenue hit **$14.2M** (+18% YTD) with operating margins tracking at **24%** (exceeding the target of 22%). APAC expansion shows strong product-market fit, and AI analysis forecasts sustained momentum into Q4.
            </p>
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="p-4 rounded-xl bg-white/5 border border-white/5">
              <p className="text-xs font-bold text-[#94A3B8] uppercase">Q3 Target Status</p>
              <p className="text-lg font-bold text-white mt-1">Exceeding Plan</p>
              <p className="text-xs text-[#10B981] mt-1">+2% margin delta</p>
            </div>
            <div className="p-4 rounded-xl bg-white/5 border border-white/5">
              <p className="text-xs font-bold text-[#94A3B8] uppercase">Risk Vector</p>
              <p className="text-lg font-bold text-white mt-1">Low / Managed</p>
              <p className="text-xs text-[#F59E0B] mt-1">1 Critical Item in Supply Chain</p>
            </div>
          </div>

          <div className="space-y-2">
            <p className="text-xs font-bold text-[#94A3B8] uppercase tracking-wider">Key Recommendations</p>
            <ul className="space-y-2 text-sm text-[#94A3B8]">
              <li className="flex items-start gap-2">
                <span className="text-[#5B5FFF] mt-0.5">•</span>
                <span>Proceed to term sheet on M&A TechNova acquisition.</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-[#5B5FFF] mt-0.5">•</span>
                <span>Fund APAC localized marketing spend (15% increase).</span>
              </li>
            </ul>
          </div>
        </div>

        {/* Footer */}
        <div className="p-6 border-t border-white/5 flex gap-3">
          <button onClick={onClose} className="functional-btn flex-1 py-2.5 rounded-xl bg-white/5 border border-white/10 text-[#94A3B8] hover:text-white text-sm font-bold transition-all">
            Close
          </button>
          <button
            onClick={handleDownload}
            disabled={downloading}
            className="functional-btn flex-1 py-2.5 rounded-xl bg-gradient-to-r from-[#EC4899] to-[#5B5FFF] text-white text-sm font-bold shadow-[0_0_15px_rgba(236,72,153,0.3)] hover:scale-[1.02] transition-all flex items-center justify-center gap-2 disabled:opacity-75"
          >
            {downloading ? (
              <><Loader2 size={16} className="animate-spin" /> Downloading...</>
            ) : (
              <><Download size={16} /> Download Report PDF</>
            )}
          </button>
        </div>
      </motion.div>
    </motion.div>
  );
}

function DecisionReviewModal({ decision, onClose, onApprove }) {
  const [approving, setApproving] = useState(false);

  const handleApprove = () => {
    setApproving(true);
    setTimeout(() => {
      onApprove(decision.id);
      setApproving(false);
      onClose();
    }, 1200);
  };

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="fixed inset-0 z-[100] flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm"
      onClick={onClose}
    >
      <motion.div
        initial={{ scale: 0.92, y: 20, opacity: 0 }}
        animate={{ scale: 1, y: 0, opacity: 1 }}
        exit={{ scale: 0.92, y: 20, opacity: 0 }}
        transition={{ type: 'spring', stiffness: 300, damping: 28 }}
        className="w-full max-w-md bg-[#0B1120] border border-white/10 rounded-3xl shadow-[0_30px_80px_rgba(0,0,0,0.8)] overflow-hidden"
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div className="px-6 py-5 border-b border-white/5 flex items-center justify-between">
          <div>
            <h2 className="text-base font-bold text-white font-display">Decision Briefing</h2>
            <p className="text-xs text-[#94A3B8] mt-0.5">Strategic alignment score: {decision.alignmentScore}</p>
          </div>
          <button onClick={onClose} className="functional-btn p-2 rounded-xl text-[#94A3B8] hover:text-white hover:bg-white/10 transition-colors">
            <X size={18} />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 space-y-4">
          <div className="space-y-1">
            <h3 className="font-bold text-white text-sm">{decision.title}</h3>
            <p className="text-xs text-[#94A3B8] leading-relaxed">{decision.desc}</p>
          </div>

          <div className="p-4 rounded-xl bg-white/5 border border-white/5">
            <p className="text-xs font-bold text-[#94A3B8] uppercase tracking-wider mb-2">Proposal Detail</p>
            <p className="text-xs text-white/95 leading-relaxed">{decision.fullDetail}</p>
          </div>

          <div className="flex gap-3 pt-2">
            <button onClick={onClose} className="functional-btn flex-1 py-2.5 rounded-xl bg-white/5 border border-white/10 text-[#94A3B8] hover:text-white text-sm font-bold transition-all">
              Cancel
            </button>
            <button
              onClick={handleApprove}
              disabled={approving}
              className="functional-btn flex-1 py-2.5 rounded-xl bg-[#10B981] hover:bg-[#059669] text-white text-sm font-bold shadow-[0_0_15px_rgba(16,185,129,0.3)] hover:scale-[1.02] transition-all flex items-center justify-center gap-2 disabled:opacity-75"
            >
              {approving ? (
                <><Loader2 size={16} className="animate-spin" /> Approving...</>
              ) : (
                <><Check size={16} /> Approve</>
              )}
            </button>
          </div>
        </div>
      </motion.div>
    </motion.div>
  );
}

export function ExecutivePage() {
  const [decisions, setDecisions] = useState(INITIAL_DECISIONS);
  const [showReport, setShowReport] = useState(false);
  const [reviewDecision, setReviewDecision] = useState(null);

  const handleApprove = (id) => {
    const decision = decisions.find(d => d.id === id);
    setDecisions(prev => prev.filter(d => d.id !== id));
    toast.success(`Approved: "${decision?.title}"! 🚀`);
  };

  return (
    <div className="w-full max-w-[1600px] mx-auto flex flex-col gap-8 relative z-10 h-full pb-10">

      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-end justify-between gap-4 mb-2">
        <div>
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-[#EC4899]/20 border border-[#EC4899]/30 text-[#EC4899] text-xs font-bold uppercase tracking-wider mb-3">
            <span className="w-2 h-2 rounded-full bg-[#EC4899] animate-pulse"></span> Live Sync
          </div>
          <h1 className="font-display text-3xl font-bold text-white tracking-tight mb-2 flex items-center gap-3">
            Executive Decision Center
          </h1>
          <p className="text-[#94A3B8] font-medium">CEO-level strategic overview and priority actions.</p>
        </div>
        <button
          onClick={() => setShowReport(true)}
          className="functional-btn self-start md:self-auto px-5 py-2.5 rounded-xl bg-gradient-to-r from-[#EC4899] to-[#5B5FFF] text-white text-sm font-bold shadow-[0_0_15px_rgba(236,72,153,0.4)] hover:scale-[1.02] hover:shadow-[0_0_25px_rgba(236,72,153,0.6)] transition-all"
        >
          Generate Board Report
        </button>
      </div>

      {/* Top KPIs */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <KPICard title="Total Revenue" value={14.2} prefix="$" suffix="M" desc="+18% YTD" color="#10B981" icon={<Wallet />} />
        <KPICard title="Operating Margin" value={24} suffix="%" desc="Target: 22%" color="#00D4FF" icon={<TrendingUp />} />
        <KPICard title="Customer Growth" value={18.5} suffix="%" desc="vs Q2" color="#5B5FFF" icon={<Globe2 />} />
        <KPICard title="Pending Decisions" value={decisions.length} color="#EC4899" desc="Requires Attention" icon={<CheckCircle />} />
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-3 gap-8">

        {/* Main Chart */}
        <GlassCard className="xl:col-span-2 p-6 border-white/5 bg-[#0B1120]/60 flex flex-col">
          <h3 className="text-sm font-bold text-[#94A3B8] uppercase tracking-wider mb-6">Financial Trajectory (Actual vs Target)</h3>
          <div className="w-full h-[300px]">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={financialData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                <defs>
                  <linearGradient id="colorRevenue" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#10B981" stopOpacity={0.8}/>
                    <stop offset="95%" stopColor="#10B981" stopOpacity={0}/>
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" vertical={false} />
                <XAxis dataKey="month" stroke="#94A3B8" fontSize={12} tickLine={false} axisLine={false} dy={10} />
                <YAxis stroke="#94A3B8" fontSize={12} tickLine={false} axisLine={false} />
                <Tooltip contentStyle={{ backgroundColor: '#050816', borderColor: 'rgba(255,255,255,0.1)', borderRadius: '12px' }} itemStyle={{ color: '#fff', fontWeight: 'bold' }}/>
                <Area type="monotone" dataKey="target" stroke="#94A3B8" strokeDasharray="5 5" fill="none" strokeWidth={2} name="Target" />
                <Area type="monotone" dataKey="revenue" stroke="#10B981" strokeWidth={3} fill="url(#colorRevenue)" name="Actual Revenue" />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </GlassCard>

        {/* Priority Actions */}
        <div className="space-y-6">
          <GlassCard className="p-6 border-[#EC4899]/30 bg-gradient-to-br from-[#0B1120]/90 to-[#050816]/90 relative overflow-hidden">
            <h3 className="text-sm font-bold text-white uppercase tracking-wider mb-4 flex items-center gap-2">
              <AlertTriangle size={16} className="text-[#EC4899]"/> Priority Decisions
            </h3>
            <div className="space-y-3 max-h-[350px] overflow-y-auto custom-scrollbar pr-1">
              <AnimatePresence mode="popLayout">
                {decisions.map((decision) => (
                  <motion.div
                    key={decision.id}
                    initial={{ opacity: 0, height: 0 }}
                    animate={{ opacity: 1, height: 'auto' }}
                    exit={{ opacity: 0, scale: 0.9, height: 0 }}
                    transition={{ duration: 0.3 }}
                    className="p-3 bg-white/5 border border-white/5 rounded-xl flex flex-col justify-between overflow-hidden"
                  >
                    <div>
                      <div className="flex justify-between items-start gap-2 mb-1">
                        <p className="text-white text-sm font-bold">{decision.title}</p>
                        <span className="text-[10px] font-bold text-[#EC4899] bg-[#EC4899]/20 px-2 py-0.5 rounded shrink-0">
                          {decision.alignmentScore}
                        </span>
                      </div>
                      <p className="text-[#94A3B8] text-xs mb-3 leading-relaxed">{decision.desc}</p>
                    </div>
                    <div className="flex gap-2">
                      <button
                        onClick={() => handleApprove(decision.id)}
                        className="functional-btn flex-1 py-1.5 bg-[#10B981] text-white text-xs font-bold rounded-lg hover:bg-[#059669] hover:scale-[1.02] transition-all"
                      >
                        Approve
                      </button>
                      <button
                        onClick={() => setReviewDecision(decision)}
                        className="functional-btn flex-1 py-1.5 bg-white/10 text-white text-xs font-bold rounded-lg hover:bg-white/20 hover:scale-[1.02] transition-all"
                      >
                        Review
                      </button>
                    </div>
                  </motion.div>
                ))}
              </AnimatePresence>
              {decisions.length === 0 && (
                <div className="text-center py-10">
                  <p className="text-sm font-bold text-white">All decisions resolved! 🎉</p>
                  <p className="text-xs text-[#94A3B8] mt-1">Excellent work, CEO.</p>
                </div>
              )}
            </div>
          </GlassCard>

          <GlassCard className="p-6 border-white/5 bg-[#0B1120]/60">
            <h3 className="text-sm font-bold text-[#94A3B8] uppercase tracking-wider mb-4 flex items-center gap-2">
              <Lightbulb size={16} className="text-[#00D4FF]"/> Strategic Insights
            </h3>
            <ul className="space-y-3 text-sm text-[#94A3B8]">
              <li className="flex items-start gap-2">
                <span className="text-[#00D4FF]">•</span>
                <span>AI predicts a <strong className="text-white">12% growth</strong> in the EMEA market next quarter.</span>
              </li>
              <li className="flex items-start gap-2">
                <span className="text-[#00D4FF]">•</span>
                <span>Supply chain risk elevated in Singapore. Recommend secondary suppliers.</span>
              </li>
            </ul>
          </GlassCard>
        </div>

      </div>

      {/* Modals */}
      <AnimatePresence>
        {showReport && <BoardReportModal onClose={() => setShowReport(false)} />}
        {reviewDecision && (
          <DecisionReviewModal
            decision={reviewDecision}
            onClose={() => setReviewDecision(null)}
            onApprove={handleApprove}
          />
        )}
      </AnimatePresence>
    </div>
  );
}

function KPICard({ title, value, prefix = "", suffix = "", desc, color, icon }) {
  return (
    <GlassCard hover glowColor={color} className="p-6 flex flex-col border-white/5 bg-[#0B1120]/60 relative overflow-hidden group">
      <div className="absolute top-0 right-0 w-24 h-24 blur-[40px] opacity-10 group-hover:opacity-30 transition-opacity duration-500" style={{ backgroundColor: color }} />
      <div className="flex justify-between items-center w-full mb-4">
        <div className="w-10 h-10 rounded-xl flex items-center justify-center transition-transform duration-500 group-hover:scale-110" style={{ backgroundColor: `${color}20`, color: color }}>
          {icon}
        </div>
      </div>
      <h3 className="text-xs font-bold text-[#94A3B8] uppercase tracking-wider mb-1">{title}</h3>
      <div className="text-3xl font-display font-bold text-white tracking-tight flex items-baseline gap-1">
        {prefix}<CountUp end={value} decimals={value % 1 !== 0 ? 1 : 0} duration={2} separator="," />{suffix}
      </div>
      {desc && <p className="text-xs text-[#94A3B8] mt-2 font-medium">{desc}</p>}
    </GlassCard>
  );
}
