import React, { useState } from 'react';
import { Bot, Sparkles, FileText, ShoppingCart, Activity, X, Info, Settings, Loader2, CheckCircle, Download, FileSpreadsheet } from 'lucide-react';
import { GlassCard } from '../../components/ui/GlassCard';
import { Portal } from '../../components/ui/Portal';
import { InsightPanel } from '../../components/ui/InsightPanel';
import { useNavigate } from 'react-router-dom';
import { mockDb } from '@/utils/mockDb';
import { motion, AnimatePresence } from 'framer-motion';
import toast from 'react-hot-toast';

export function AIInventoryAssistant() {
  const navigate = useNavigate();
  const [showReorderWizard, setShowReorderWizard] = useState(false);
  const [showReportModal, setShowReportModal] = useState(false);
  
  // Reorder Wizard states
  const [reorderQty, setReorderQty] = useState(850);
  const [isEditingQty, setIsEditingQty] = useState(false);
  const [confirmingOrder, setConfirmingOrder] = useState(false);
  
  // Report states
  const [generatingReport, setGeneratingReport] = useState(false);
  const [reportFormat, setReportFormat] = useState('pdf');

  const insights = [
    { text: "18 products are likely to go out of stock in 5 days.", highlight: "out of stock in 5 days" },
    { text: "Product X demand will increase next week.", highlight: "demand will increase" },
    { text: "Warehouse B is nearing capacity.", highlight: "nearing capacity" },
    { text: "Supplier ABC has delayed shipments.", highlight: "delayed shipments" },
  ];

  const handleConfirmOrder = () => {
    setConfirmingOrder(true);
    setTimeout(() => {
      mockDb.updateProductStock('SKU-2038', reorderQty);
      setConfirmingOrder(false);
      setShowReorderWizard(false);
      toast.success(`Purchase Order for ${reorderQty} units confirmed!`, { icon: '📝' });
      window.dispatchEvent(new Event('storage'));
    }, 1500);
  };

  const handleGenerateReport = () => {
    setGeneratingReport(true);
    toast.loading('Compiling data columns & computing tables...');
    
    setTimeout(() => {
      const products = mockDb.getProducts();
      const lowStock = products.filter(p => p.stock <= p.minStock);
      
      const reportHTML = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Business Brain Executive Inventory Report</title>
  <style>
    body { font-family: 'Inter', sans-serif; padding: 40px; color: #1e293b; background: #fff; line-height: 1.5; }
    .card { max-width: 900px; margin: 0 auto; border: 1px solid #e2e8f0; padding: 40px; border-radius: 16px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.05); }
    .header { display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid #7c3aed; padding-bottom: 20px; margin-bottom: 30px; }
    h1 { color: #7c3aed; margin: 0; font-size: 24px; font-weight: 800; }
    .logo { font-size: 20px; font-weight: 900; color: #0f172a; }
    .meta { font-size: 12px; color: #64748b; margin-top: 5px; }
    h2 { font-size: 15px; text-transform: uppercase; color: #334155; border-bottom: 1px solid #f1f5f9; padding-bottom: 8px; margin-top: 25px; letter-spacing: 0.5px; }
    table { width: 100%; border-collapse: collapse; margin-top: 10px; }
    th, td { padding: 12px 10px; text-align: left; border-bottom: 1px solid #f1f5f9; font-size: 12px; }
    th { background: #f8fafc; font-weight: 700; color: #475569; }
    .badge { padding: 3px 8px; border-radius: 6px; font-size: 10px; font-weight: 700; text-transform: uppercase; }
    .badge-low { background: #fef3c7; color: #d97706; }
    .badge-ok { background: #dcfce7; color: #15803d; }
    .summary-grid { display: grid; grid-template-cols: repeat(4, 1fr); gap: 15px; margin-bottom: 20px; }
    .stat { background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 15px; text-align: center; }
    .stat-val { font-size: 20px; font-weight: 800; color: #0f172a; }
    .stat-lbl { font-size: 10px; color: #64748b; text-transform: uppercase; margin-top: 2px; }
    .footer { text-align: center; font-size: 10px; color: #94a3b8; margin-top: 40px; border-top: 1px solid #f1f5f9; padding-top: 15px; }
  </style>
</head>
<body>
  <div class="card">
    <div class="header">
      <div>
        <h1>Executive Inventory Report</h1>
        <div class="meta">Generated by Business Brain System • ${new Date().toLocaleString()}</div>
      </div>
      <div class="logo">Business Brain</div>
    </div>
    <div class="summary-grid">
      <div class="stat">
        <div class="stat-val">${products.length}</div>
        <div class="stat-lbl">Active SKUs</div>
      </div>
      <div class="stat">
        <div class="stat-val">${products.reduce((sum, p) => sum + p.stock, 0).toLocaleString()}</div>
        <div class="stat-lbl">Total Stock</div>
      </div>
      <div class="stat">
        <div class="stat-val">${lowStock.length}</div>
        <div class="stat-lbl">Low Stock SKUs</div>
      </div>
      <div class="stat">
        <div class="stat-val">$${products.reduce((sum, p) => sum + (p.stock * p.purchasePrice), 0).toLocaleString()}</div>
        <div class="stat-lbl">Total Asset Value</div>
      </div>
    </div>
    <div class="footer">
      This document is confidential and proprietary to Business Brain. Generated for internal audit and operations optimization.
    </div>
  </div>
</body>
</html>`;

      const blob = new Blob([reportHTML], { type: 'text/html;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      
      const fileExt = reportFormat === 'excel' ? 'xls' : 'html';
      const fileName = `Inventory_Report_${new Date().toISOString().slice(0, 10)}.${fileExt}`;
      a.download = fileName;
      
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);

      setGeneratingReport(false);
      setShowReportModal(false);
      toast.dismiss();
      toast.success(`Inventory Report successfully downloaded as ${reportFormat.toUpperCase()}`);
    }, 1500);
  };

  return (
    <>
      <InsightPanel
        moduleName="Inventory"
        title="Inventory AI"
        subtitle="Stock Insights"
        badgeText="AI Predictor Active"
        description="I have analyzed your warehouse capacities, historical sales trends, and supplier lead times. Here are the critical inventory actions for today."
        insights={insights}
        recommendationsModal={RecommendationsModal}
        themeColor="#7C3AED"
      />

      <div className="flex justify-center gap-4 mt-[-24px] mb-6 z-10 relative">
        <button onClick={() => setShowReorderWizard(true)} className="px-4 py-2.5 rounded-xl bg-[#7C3AED]/15 border border-[#7C3AED]/30 text-[#7C3AED] text-xs font-bold hover:bg-[#7C3AED]/25 transition-all flex items-center gap-2 cursor-pointer">
          <ShoppingCart size={14} /> Reorder Wizard
        </button>
        <button onClick={() => navigate('/app/inventory/forecast')} className="px-4 py-2.5 rounded-xl bg-[#EC4899]/15 border border-[#EC4899]/30 text-[#EC4899] text-xs font-bold hover:bg-[#EC4899]/25 transition-all flex items-center gap-2 cursor-pointer">
          <Activity size={14} /> View AI Forecast
        </button>
        <button onClick={() => setShowReportModal(true)} className="px-4 py-2.5 rounded-xl bg-[#00D4FF]/15 border border-[#00D4FF]/30 text-[#00D4FF] text-xs font-bold hover:bg-[#00D4FF]/25 transition-all flex items-center gap-2 cursor-pointer">
          <FileText size={14} /> Generate Report
        </button>
      </div>

      {/* ── AI Reorder Wizard Modal ── */}
      <AnimatePresence>
        {showReorderWizard && (
          <Portal>
            <div className="fixed inset-0 z-[999] flex items-center justify-center p-4" style={{ backgroundColor: 'rgba(5,8,22,0.85)', backdropFilter: 'blur(8px)' }}>
              <motion.div
                initial={{ opacity: 0, scale: 0.95, y: 20 }}
                animate={{ opacity: 1, scale: 1, y: 0 }}
                exit={{ opacity: 0, scale: 0.95 }}
                className="w-full max-w-lg rounded-2xl border border-[#7C3AED]/20 bg-[#0B1120] shadow-2xl p-6 relative overflow-hidden"
              >
                <div className="flex items-center justify-between pb-4 border-b border-white/5 mb-4">
                  <h2 className="text-xl font-bold text-white flex items-center gap-2">
                    <ShoppingCart className="text-[#7C3AED]" size={20} /> AI Reorder Stock Wizard
                  </h2>
                  <button onClick={() => setShowReorderWizard(false)} className="text-[#94A3B8] hover:text-white transition-colors">
                    <X size={20} />
                  </button>
                </div>

                <div className="space-y-4">
                  <div className="flex items-start gap-3 p-3 rounded-xl bg-[#7C3AED]/10 border border-[#7C3AED]/20">
                    <Info size={16} className="text-[#EC4899] shrink-0 mt-0.5" />
                    <div>
                      <p className="text-xs font-bold text-white mb-0.5">AI Recommendation</p>
                      <p className="text-[11px] text-[#94A3B8] leading-relaxed">
                        Urgent restocking advised for Packaging Unit B-200. Projected Q3/Q4 surges threaten current buffer limits. Expected stockout within 5 days if order is delayed.
                      </p>
                    </div>
                  </div>

                  <div className="grid grid-cols-2 gap-4">
                    <div className="p-3 bg-white/5 border border-white/5 rounded-xl">
                      <span className="text-[10px] font-bold text-[#94A3B8] uppercase block mb-1">Stock SKU-2038</span>
                      <span className="text-sm font-bold text-white">85 units remaining</span>
                    </div>
                    <div className="p-3 bg-white/5 border border-white/5 rounded-xl">
                      <span className="text-[10px] font-bold text-[#94A3B8] uppercase block mb-1">Supplier Ref</span>
                      <span className="text-sm font-bold text-white">BoxCo Supply</span>
                    </div>
                  </div>

                  <div className="p-4 bg-white/5 border border-white/5 rounded-xl">
                    <div className="flex justify-between items-center mb-3">
                      <span className="text-xs font-bold text-[#94A3B8] uppercase">Order Quantity</span>
                      <button 
                        type="button"
                        onClick={() => setIsEditingQty(!isEditingQty)}
                        className="text-[11px] text-[#00D4FF] hover:underline"
                      >
                        {isEditingQty ? 'Done' : 'Change Quantity'}
                      </button>
                    </div>
                    
                    {isEditingQty ? (
                      <div className="flex gap-2 mb-2">
                        <input
                          type="number"
                          value={reorderQty}
                          onChange={e => setReorderQty(parseInt(e.target.value) || 0)}
                          className="flex-1 px-3 py-1.5 text-xs rounded bg-white/5 border border-white/10 text-white focus:outline-none focus:border-[#7C3AED]"
                        />
                      </div>
                    ) : (
                      <p className="text-2xl font-display font-bold text-[#7C3AED]">{reorderQty} <span className="text-xs text-[#94A3B8]">units suggested</span></p>
                    )}

                    <div className="grid grid-cols-2 gap-2 mt-3 pt-3 border-t border-white/5 text-xs">
                      <div className="flex justify-between">
                        <span className="text-white/40">Est. Cost:</span>
                        <span className="text-white font-bold">${(reorderQty * 12).toLocaleString()}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-white/40">Delivery Time:</span>
                        <span className="text-white font-bold">5 Days</span>
                      </div>
                    </div>
                  </div>

                  <div className="flex gap-3 justify-end pt-4 border-t border-white/5">
                    <button
                      type="button"
                      onClick={() => setShowReorderWizard(false)}
                      className="px-4 py-2 rounded-xl bg-white/5 text-white text-sm font-bold hover:bg-white/10 transition-colors"
                    >
                      Cancel
                    </button>
                    <button
                      onClick={handleConfirmOrder}
                      disabled={confirmingOrder}
                      className="px-5 py-2 rounded-xl bg-gradient-to-r from-[#7C3AED] to-[#EC4899] text-white text-sm font-bold hover:scale-[1.02] transition-transform flex items-center gap-2"
                    >
                      {confirmingOrder ? 'Confirming...' : 'Confirm Order'}
                    </button>
                  </div>
                </div>
              </motion.div>
            </div>
          </Portal>
        )}
      </AnimatePresence>

      {/* ── Generate Report Modal ── */}
      <AnimatePresence>
        {showReportModal && (
          <Portal>
            <div className="fixed inset-0 z-[999] flex items-center justify-center p-4" style={{ backgroundColor: 'rgba(5,8,22,0.85)', backdropFilter: 'blur(8px)' }}>
              <motion.div
                initial={{ opacity: 0, scale: 0.95, y: 20 }}
                animate={{ opacity: 1, scale: 1, y: 0 }}
                exit={{ opacity: 0, scale: 0.95 }}
                className="w-full max-w-md rounded-2xl border border-white/10 bg-[#0B1120] shadow-2xl p-6 relative overflow-hidden"
              >
                <div className="flex items-center justify-between pb-4 border-b border-white/5 mb-4">
                  <h2 className="text-xl font-bold text-white flex items-center gap-2">
                    <FileText className="text-[#00D4FF]" size={20} /> Compile Corporate Report
                  </h2>
                  <button onClick={() => setShowReportModal(false)} className="text-[#94A3B8] hover:text-white transition-colors">
                    <X size={20} />
                  </button>
                </div>

                <div className="space-y-4">
                  <p className="text-xs text-[#94A3B8] leading-relaxed">
                    Configure your stock telemetry audit sheet. The compiler compiles active product logs, warehouse loads, and supplier Grades.
                  </p>

                  <div>
                    <label className="block text-xs font-bold text-[#94A3B8] uppercase tracking-wider mb-2">Export Format</label>
                    <div className="grid grid-cols-2 gap-3">
                      <button
                        onClick={() => setReportFormat('pdf')}
                        className={`p-3 rounded-xl border flex flex-col items-center justify-center gap-2 transition-all ${
                          reportFormat === 'pdf' 
                            ? 'bg-[#7C3AED]/20 border-[#7C3AED] text-white' 
                            : 'bg-white/5 border-white/10 text-[#94A3B8] hover:text-white'
                        }`}
                      >
                        <FileText size={24} />
                        <span className="text-xs font-bold">Adobe PDF</span>
                      </button>
                      <button
                        onClick={() => setReportFormat('excel')}
                        className={`p-3 rounded-xl border flex flex-col items-center justify-center gap-2 transition-all ${
                          reportFormat === 'excel' 
                            ? 'bg-[#10B981]/20 border-[#10B981] text-white' 
                            : 'bg-white/5 border-white/10 text-[#94A3B8] hover:text-white'
                        }`}
                      >
                        <FileSpreadsheet size={24} />
                        <span className="text-xs font-bold">Microsoft Excel</span>
                      </button>
                    </div>
                  </div>

                  <div className="flex gap-3 justify-end pt-4 border-t border-white/5">
                    <button
                      type="button"
                      onClick={() => setShowReportModal(false)}
                      className="px-4 py-2 rounded-xl bg-white/5 text-white text-sm font-bold hover:bg-white/10 transition-colors"
                    >
                      Cancel
                    </button>
                    <button
                      onClick={handleGenerateReport}
                      disabled={generatingReport}
                      className="px-5 py-2.5 rounded-xl bg-gradient-to-r from-[#00D4FF] to-[#5B5FFF] text-white text-sm font-bold hover:scale-[1.02] transition-all flex items-center justify-center gap-2"
                    >
                      {generatingReport ? 'Compiling...' : 'Compile Now'}
                    </button>
                  </div>
                </div>
              </motion.div>
            </div>
          </Portal>
        )}
      </AnimatePresence>
    </>
  );
}

function RecommendationsModal({ onClose }) {
  return (
    <Portal>
      <div className="fixed inset-0 z-[999] flex items-center justify-center p-4" style={{ backgroundColor: 'rgba(5,8,22,0.85)', backdropFilter: 'blur(8px)' }}>
        <div className="w-full max-w-md rounded-2xl border border-white/10 bg-[#0B1120] shadow-2xl p-6 relative overflow-hidden">
          <button onClick={onClose} className="absolute top-4 right-4 text-[#94A3B8] hover:text-white transition-colors z-20"><X size={20} /></button>
          <h3 className="text-lg font-bold text-white mb-4">Stock Restock Recommendations</h3>
          <p className="text-sm text-[#94A3B8] leading-relaxed mb-4">
            AI recommends creating immediate purchase order for Packaging Unit B-200 to meet upcoming customer demand spikes.
          </p>
          <button onClick={onClose} className="w-full py-2.5 rounded-xl bg-white/5 border border-white/10 text-white text-sm font-bold hover:bg-white/10">Close</button>
        </div>
      </div>
    </Portal>
  );
}
