import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { ArrowLeft, BrainCircuit, Download, TrendingUp, Calendar, AlertCircle, Sparkles, HelpCircle } from 'lucide-react';
import { GlassCard } from '@/components/ui/GlassCard';
import { AreaChart, Area, BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, Legend } from 'recharts';
import toast from 'react-hot-toast';

const mockForecastData = [
  { month: 'Jul', actualStock: 1200, forecastDemand: 950, safetyStock: 300 },
  { month: 'Aug', actualStock: 1100, forecastDemand: 1050, safetyStock: 300 },
  { month: 'Sep', actualStock: 950, forecastDemand: 1200, safetyStock: 300 }, // Under forecast demand
  { month: 'Oct', actualStock: 1300, forecastDemand: 1100, safetyStock: 300 },
  { month: 'Nov', actualStock: 1400, forecastDemand: 1400, safetyStock: 350 },
  { month: 'Dec', actualStock: 1600, forecastDemand: 1750, safetyStock: 400 }, // Seasonal Spike
];

const mockSeasonalData = [
  { season: 'Q1 (Spring)', growth: '+12%', status: 'Moderate Demand', color: '#00D4FF' },
  { season: 'Q2 (Summer)', growth: '+18%', status: 'High Demand', color: '#10B981' },
  { season: 'Q3 (Autumn)', growth: '+8%', status: 'Stable Demand', color: '#5B5FFF' },
  { season: 'Q4 (Winter/Holiday)', growth: '+32%', status: 'Peak Demand Spike', color: '#EC4899' },
];

export function InventoryForecast() {
  const navigate = useNavigate();
  const [downloading, setDownloading] = useState(false);

  const handleDownloadPDF = () => {
    setDownloading(true);
    toast.loading('Compiling forecast charts & AI predictions...');
    
    setTimeout(() => {
      const reportHTML = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Inventory Demand Forecast Report</title>
  <style>
    body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 40px; color: #333; background: #fff; }
    .header { border-bottom: 2px solid #5B5FFF; padding-bottom: 15px; margin-bottom: 30px; }
    h1 { color: #5B5FFF; margin: 0 0 5px 0; font-size: 26px; }
    .meta { color: #777; font-size: 12px; }
    .section { margin-bottom: 25px; }
    h2 { color: #333; font-size: 16px; border-bottom: 1px solid #eee; padding-bottom: 5px; }
    table { width: 100%; border-collapse: collapse; margin-top: 10px; }
    th, td { padding: 10px; text-align: left; border-bottom: 1px solid #eee; font-size: 13px; }
    th { background: #f9f9f9; color: #555; }
    .alert { background: #fff8e1; border-left: 4px solid #ffb300; padding: 10px; font-size: 13px; margin: 15px 0; }
    .recommendation { background: #e8f5e9; border-left: 4px solid #4caf50; padding: 10px; font-size: 13px; }
    .footer { text-align: center; font-size: 10px; color: #aaa; margin-top: 50px; border-top: 1px solid #eee; padding-top: 15px; }
  </style>
</head>
<body>
  <div class="header">
    <h1>AI Inventory Demand Forecast Report</h1>
    <div class="meta">Generated by Business Brain Predictive AI • ${new Date().toLocaleDateString()}</div>
  </div>
  
  <div class="section">
    <h2>6-Month Stock vs Forecast Demand</h2>
    <table>
      <thead>
        <tr>
          <th>Month</th>
          <th>Actual/Projected Stock</th>
          <th>Forecasted Demand</th>
          <th>Safety Stock Threshold</th>
        </tr>
      </thead>
      <tbody>
        ${mockForecastData.map(d => `
          <tr>
            <td><strong>${d.month}</strong></td>
            <td>${d.actualStock} units</td>
            <td>${d.forecastDemand} units</td>
            <td>${d.safetyStock} units</td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  </div>

  <div class="alert">
    <strong>⚠ Supply Chain Forecast Warning:</strong> September forecasted demand (${mockForecastData[2].forecastDemand} units) exceeds projected actual stock (${mockForecastData[2].actualStock} units). Immediate reorder wizard confirmation is advised in August to avoid stockouts.
  </div>

  <div class="section">
    <h2>Seasonal Demand Trajectory</h2>
    <table>
      <thead>
        <tr>
          <th>Quarter</th>
          <th>Growth Prediction</th>
          <th>Demand Status</th>
        </tr>
      </thead>
      <tbody>
        ${mockSeasonalData.map(s => `
          <tr>
            <td><strong>${s.season}</strong></td>
            <td style="color: #4caf50; font-weight: bold;">${s.growth}</td>
            <td>${s.status}</td>
          </tr>
        `).join('')}
      </tbody>
    </table>
  </div>

  <div class="section">
    <h2>AI Strategic Stock Recommendations</h2>
    <div class="recommendation">
      <strong>Holiday Spike Alert:</strong> Winter holiday spike demands an inventory buffer expansion (+20%) starting late November. Automate shipping pipelines to reduce warehouse congestion.
    </div>
  </div>

  <div class="footer">
    © ${new Date().getFullYear()} Business Brain Inc. Confidential and Proprietary.
  </div>
</body>
</html>`;

      const blob = new Blob([reportHTML], { type: 'text/html;charset=utf-8' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `Inventory_Forecast_Report_${new Date().toISOString().slice(0, 10)}.html`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      toast.dismiss();
      toast.success('Forecast report downloaded!');
      setDownloading(false);
    }, 1500);
  };

  return (
    <div className="w-full max-w-[1600px] mx-auto flex flex-col gap-8 relative z-10 h-full pb-10">
      
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div className="flex items-center gap-4">
          <button 
            onClick={() => navigate('/app/inventory')}
            className="w-10 h-10 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center hover:bg-white/10 text-white transition-colors"
          >
            <ArrowLeft size={18} />
          </button>
          <div>
            <h1 className="font-display text-3xl font-bold text-white tracking-tight mb-1 flex items-center gap-3">
              <BrainCircuit className="text-[#00D4FF]" size={28} />
              AI Demand Forecasting
            </h1>
            <p className="text-[#94A3B8] font-medium">Predictive modeling of safety stock, sales spikes, and seasonal trends.</p>
          </div>
        </div>
        
        <button
          onClick={handleDownloadPDF}
          disabled={downloading}
          className="px-5 py-2.5 rounded-xl bg-gradient-to-r from-[#00D4FF] to-[#5B5FFF] text-white text-sm font-bold shadow-lg hover:scale-[1.02] transition-transform flex items-center gap-2"
        >
          <Download size={16} /> Download PDF
        </button>
      </div>

      {/* Graphs */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        
        {/* Main Forecast Chart */}
        <GlassCard className="lg:col-span-2 p-6 border-white/5 bg-[#0B1120]/60 flex flex-col gap-6">
          <div>
            <h3 className="font-bold text-white text-base">Stock Levels vs Projected Demand</h3>
            <p className="text-xs text-[#94A3B8]">6-month future prediction containing safety margins</p>
          </div>
          
          <div className="w-full h-[300px]">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={mockForecastData} margin={{ top: 10, right: 10, left: -20, bottom: 0 }}>
                <defs>
                  <linearGradient id="colorStock" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#00D4FF" stopOpacity={0.3}/>
                    <stop offset="95%" stopColor="#00D4FF" stopOpacity={0}/>
                  </linearGradient>
                  <linearGradient id="colorDemand" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="#EC4899" stopOpacity={0.3}/>
                    <stop offset="95%" stopColor="#EC4899" stopOpacity={0}/>
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" stroke="rgba(255,255,255,0.05)" vertical={false} />
                <XAxis dataKey="month" stroke="#94A3B8" fontSize={11} tickLine={false} axisLine={false} />
                <YAxis stroke="#94A3B8" fontSize={11} tickLine={false} axisLine={false} />
                <Tooltip
                  contentStyle={{ backgroundColor: '#050816', borderColor: 'rgba(255,255,255,0.1)', borderRadius: '12px' }}
                  itemStyle={{ color: '#fff', fontWeight: 'bold' }}
                />
                <Legend />
                <Area type="monotone" name="Projected Stock" dataKey="actualStock" stroke="#00D4FF" strokeWidth={2} fillOpacity={1} fill="url(#colorStock)" />
                <Area type="monotone" name="Forecasted Demand" dataKey="forecastDemand" stroke="#EC4899" strokeWidth={2} fillOpacity={1} fill="url(#colorDemand)" />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </GlassCard>

        {/* AI Recommendations */}
        <div className="flex flex-col gap-6">
          <GlassCard className="p-6 border-white/5 bg-[#0B1120]/60 relative overflow-hidden flex-1">
            <h3 className="font-bold text-white text-base mb-4 flex items-center gap-2">
              <Sparkles className="text-[#00D4FF]" size={16} /> AI Insights
            </h3>
            <div className="space-y-4">
              <div className="p-3.5 rounded-xl bg-white/5 border border-white/5">
                <p className="text-xs font-bold text-white mb-1">September Stockout Warning</p>
                <p className="text-[11px] text-[#94A3B8] leading-relaxed">
                  Projected demand of 1,200 units in September will deplete current safety stock levels. A minimum order of 300 units should be processed before Aug 25.
                </p>
              </div>
              <div className="p-3.5 rounded-xl bg-[#EC4899]/10 border border-[#EC4899]/20">
                <p className="text-xs font-bold text-[#EC4899] mb-1">Holiday Demand Surge</p>
                <p className="text-[11px] text-[#94A3B8] leading-relaxed">
                  Winter demand is modeled to increase by 32%. Order pipelines should be finalized in October to prevent logistics bottlenecks.
                </p>
              </div>
            </div>
          </GlassCard>
        </div>
      </div>

      {/* Bottom widgets */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        
        {/* Seasonal demand table */}
        <GlassCard className="p-6 border-white/5 bg-[#0B1120]/60">
          <h3 className="font-bold text-white text-base mb-4 flex items-center gap-2">
            <Calendar className="text-[#5B5FFF]" size={18} /> Seasonal Demand Projection
          </h3>
          <div className="space-y-3">
            {mockSeasonalData.map(s => (
              <div key={s.season} className="flex justify-between items-center p-3 rounded-xl bg-white/5 border border-white/5">
                <div>
                  <p className="text-sm font-bold text-white">{s.season}</p>
                  <p className="text-xs text-[#94A3B8]">{s.status}</p>
                </div>
                <span style={{ color: s.color }} className="text-sm font-display font-bold">
                  {s.growth}
                </span>
              </div>
            ))}
          </div>
        </GlassCard>

        {/* Stock trends summary */}
        <GlassCard className="p-6 border-white/5 bg-[#0B1120]/60 flex flex-col justify-between">
          <div>
            <h3 className="font-bold text-white text-base mb-4 flex items-center gap-2">
              <TrendingUp className="text-[#10B981]" size={18} /> Stock Trends Summary
            </h3>
            <p className="text-xs text-[#94A3B8] leading-relaxed mb-4">
              Your overall inventory turns have improved by 14% compared to the previous quarter. AI modeling indicates average inventory holding costs can be reduced by 5.2% if cross-docking is enabled.
            </p>
          </div>
          <div className="flex gap-4">
            <div className="flex-1 bg-white/5 p-4 rounded-xl text-center border border-white/5">
              <p className="text-2xl font-display font-bold text-[#10B981]">14.2%</p>
              <p className="text-[10px] text-[#94A3B8] uppercase tracking-wider">Inventory Turns</p>
            </div>
            <div className="flex-1 bg-white/5 p-4 rounded-xl text-center border border-white/5">
              <p className="text-2xl font-display font-bold text-[#00D4FF]">-5.2%</p>
              <p className="text-[10px] text-[#94A3B8] uppercase tracking-wider">Holding Costs</p>
            </div>
          </div>
        </GlassCard>

      </div>

    </div>
  );
}
